name: Deploy Versioned Documentation

on:
  push:
    branches: [main]
    tags: ["v*"] # Trigger on pushes to main AND on pushes of tags like v0.1, v1.0.0
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-deploy-docs:
    name: Build and Deploy Docs to GitHub Pages
    if: |
      github.event_name == 'push' &&
      (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/uv
          key: ${{ runner.os }}-uv-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-pip-
            ${{ runner.os }}-pip-

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy with Mike
        id: publish
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/v}"
            echo "Deploying tagged version: $VERSION_TAG"
            mike deploy "$VERSION_TAG" latest --push --update-aliases
            mike set-default --push latest
          elif [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "Deploying main branch to 'main' version with 'dev' alias"
            mike deploy main dev --push --update-aliases
          else
            echo "Skipping deployment for ref: $GITHUB_REF"
          fi

  build-docs-on-pr:
    name: Build Docs (PR Check)
    if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/uv
          key: ${{ runner.os }}-uv-pip-pr-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-pip-pr-
            ${{ runner.os }}-uv-pip-
            ${{ runner.os }}-pip-

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Build site with MkDocs (no deploy)
        run: |
          mkdocs build --strict
